### ISSUE TITLE
BGR vs RGB error when creating image for iOS inference?

### ISSUE THREAD

**Issue by jim-meyer** [csharpseattle/tensorflowiOS#10]
https://github.com/csharpseattle/tensorflowiOS/blob/17101b75dec2b8b53496a3e45878f86e53f3b32a/objC/Tensorflow/TensorflowGraph.mm#L298

Tensorflow trains using images based on the image pixel tuples being in Blue/Green/Red (BGR) order. But on iOS the image pixel buffer at this point is in Red/Green/Blue (RGB) order. And this code is just copying straight over. So reds are being converted to blues and vice versa before inference is being run on the pixels.
I started having better accuracy on my iPhone when I changed this to copy red-to-red and blue-to-blue like this:
destPixel[tensorChannels - c - 1] = srcPixels[c];

**Comment by csharpseattle** [comment]
Interesting find.   I request a BGR Pixel Buffer in `CameraPreviewView` but a increase in accuracy is always welcome. 
` NSDictionary *newSettings = @{ (NSString *)kCVPixelBufferPixelFormatTypeKey :@(kCVPixelFormatType_32BGRA) };`

I'll take a look and report back.

**Comment by jim-meyer** [comment]
Hmm, ok you might be right. I've heavily changed this code and stopped
using the camera in my use case, instead relying on images from the Photo
Library. So now you have me pretty much convinced that the bug is in my
code where I'm reading in images in RGB order though the code implicitly
assumed BGR. I'll dig further on my end.

**Comment by csharpseattle** [comment]
I am aware of a case where the copy you refer to might not be entirely correct.  Ideally there would be a selective copy of pixel based on the orientation of the pixel buffer.  I think this comes into play when you start in landscape and rotate to portrait.  What really should happen is a square around the center of the buffer should be copied so that there is no distortion of the image going into the model.  

However, I believe this is a different bug and not what your are seeing.  Might improve accuracy though.

**Comment by jim-meyer** [comment]
Sorry for the false report. Mea culpa. I now see that the code is using BGR options on the camera. And several comments in the code that make this clear. I'm 100% positive that the problem is me passing RGB images to a function that expects BGR. Thus I'm closing this since the onus is on me to pass the images as BGR to this code.
